# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-09 10:32
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uid', models.BigIntegerField()),
                ('type', models.IntegerField()),
                ('s_password', models.CharField(default=b'password', max_length=255)),
                ('phone', models.CharField(default=b'', max_length=100)),
                ('mobile', models.CharField(default=b'', max_length=100)),
                ('billing_address', models.CharField(default=b'{}', max_length=255)),
                ('shipping_address', models.CharField(default=b'{}', max_length=255)),
                ('iccid', models.CharField(default=b'', max_length=100)),
                ('consumer_id', models.CharField(default=b'', max_length=100)),
                ('language', models.IntegerField(default=1)),
                ('invoice_nr', models.CharField(default=b'', max_length=100)),
                ('order_nr', models.CharField(default=b'', max_length=100)),
                ('subscr_month', models.IntegerField(default=6)),
                ('subscr_data', models.IntegerField(default=5)),
                ('subscr_type', models.IntegerField(default=1)),
                ('note', models.TextField(default=b'', max_length=1024)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TblIccidList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(default=b'', max_length=100)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TblMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
                ('parent_id', models.IntegerField()),
                ('has_child', models.IntegerField()),
                ('icon', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('privilege', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TblTrafficData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(default=b'', max_length=100)),
                ('date', models.DateField()),
                ('traffic', models.FloatField()),
            ],
        ),
    ]
